moviesproject/moviesapp/urls.py
from . import views
from django.urls import path
app_name='moviesapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:movie_id>/',views.update_movie,name='update_movie'),
    path('delete/<int:movie_id>/',views.delete_movie,name='delete_movie')
]

moviesproject/moviesproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('moviesapp.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

moviesproject/moviesapp/models.py
from django.db import models

# Create your models here.
class Movie_details(models.Model):
    movie_name=models.CharField(max_length=50)
    movie_desc=models.TextField()
    movie_year=models.IntegerField()
    movie_image=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.movie_name

moviesproject/moviesapp/forms.py
from django import forms
from . models import Movie_details

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie_details
        fields=['movie_name','movie_desc','movie_year','movie_image']

moviesproject/moviesapp/views.py
from django.http import HttpResponse
from . models import Movie_details
from django.shortcuts import render, redirect
from .forms import MovieForm

# Create your views here.
def index(request):
    ##get all data
    obj=Movie_details.objects.all()
    return render(request,"index.html",{'movie_list':obj})
def details(request,movie_id):
    #get data of particular id
    obj= Movie_details.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':obj})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('movie_name',)
        desc = request.POST.get('movie_desc', )
        year = request.POST.get('movie_year', )
        img = request.FILES['movie_image']
        movie=Movie_details(movie_name=name,movie_desc=desc,movie_year=year,movie_image=img)
        movie.save()
    return render(request,"add.html")
def update_movie(request,movie_id):
    movie=Movie_details.objects.get(id=movie_id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'movie':movie})
def delete_movie(request,movie_id):
    if request.method=='POST':
        movie=Movie_details.objects.get(id=movie_id)
        movie.delete()
        return  redirect('/')
    return render(request,"delete.html")

moviesproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form name="add_movie" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="movie_name" placeholder="Enter movie name"><br>
    <input type="text" name="movie_desc" placeholder="Enter movie description"><br>
    <input type="number" name="movie_year" placeholder="Enter movie year"><br>
    <input type="file" name="movie_image"><br>
    <input type="submit">
</form>
{% endblock %}

moviesproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" >
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body%}
{% endblock %}
</body>
</html>

moviesproject/templates/delete.html
<form method="post">
  {% csrf_token %}
  Are you want to delete this Movie?
  <input type="submit">
  </form>

moviesproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row mo">
        <div class="col-md-4">
            <img src="{{movie.movie_image.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <h3>{{movie.movie_name}}</h3>
            <p>{{movie.movie_desc}}</p>
            <p>{{movie.movie_year}}</p>
                <a href="{% url 'moviesapp:update_movie' movie.id %}" class="btn btn-warning a1">Update</a>
                <a href="{% url 'moviesapp:delete_movie' movie.id %}" class="btn btn-danger a1">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

moviesproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-6">
      <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
        
        <input type="submit">
      </form>
    </div>
  </div>
</div>
{% endblock %}

moviesproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{ i.movie_image.url }}" alt="" width="100" height="200">
                <div class="card-body">
                    <h5 class="card-title">{{i.movie_name}}</h5>
                    <a href="{% url 'moviesapp:details' i.id %}" class="btn btn-success">More Info</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}